server.port=5454

spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:ecommerce_project}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Password@143}

#ORM s/w specific properties
#spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#logging.level.org.springframework=DEBUG
razorpay.api.key=rzp_test_ST46b7ug1odvP6
razorpay.api.secret=dRHIsFADl8ODueBXT6QP6cAK

stripe.api.key=your stripe api key

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=zaribshaik786@gmail.com
spring.mail.password=evar khyp hnea qfqv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.devtools.livereload.enabled=true

#ai
gemini.api.key=qpdsxkzsmuofvsdh
